import type { MetadataRoute } from 'next'

export const dynamic = 'force-static'

const siteUrl = 'https://legionremixhub.com'

const routes = [
  '/',
  '/roadmap',
  '/news',
  '/news/phase-5-infinite-echoes-live',
  '/news/housing-decor-legion-remix',
  '/news/fragmented-mementos-new-sources',
  '/news/moratari-quest-skip-fixes',
  '/news/hidden-artifact-appearances-hotfixed',
  '/news/phase-4-legion-remix-now-live',
  '/news/legion-remix-character-transfer',
  '/news/phase-3-legion-remix-now-live',
  '/news/class-mount-quests-hotfixed',
  '/guides',
  '/guides/argus-campaign',
  '/guides/release-schedule',
  '/guides/getting-started',
  '/guides/leveling',
  '/guides/bronze-farming',
  '/guides/legion-assaults',
  '/guides/broken-shore-legionfall',
  '/guides/ancient-mana',
  '/guides/fragmented-mementos',
  '/guides/dungeons',
  '/guides/raids',
  '/guides/infinite-knowledge',
  '/guides/challiane-vineyards',
  '/guides/bronze-vendors',
  '/guides/hunter-pets',
  '/guides/sargerei-commanders-regalia',
  '/calculator',
  '/guides/kaldorei-royal-vestments',
  '/guides/suramar-campaign',
  '/rewards',
  '/rewards/mounts',
  '/rewards/pets',
  '/rewards/toys',
  '/rewards/transmog',
  '/rewards/housing',
  '/rewards/reputation',
  '/reputation',
  '/reputation/army-of-the-light',
  '/reputation/argussian-reach',
  '/reputation/court-of-farondis',
  '/reputation/dreamweavers',
  '/reputation/highmountain-tribe',
  '/reputation/the-nightfallen',
  '/reputation/the-wardens',
  '/reputation/valarjar',
  '/reputation/armies-of-legionfall',
  '/reputation/kirin-tor',
  '/classes',
  '/guides/class-mounts',
  '/faq',
  '/classes/warrior',
  '/classes/paladin',
  '/classes/hunter',
  '/classes/rogue',
  '/classes/priest',
  '/classes/death-knight',
  '/classes/shaman',
  '/classes/mage',
  '/classes/warlock',
  '/classes/monk',
  '/classes/druid',
  '/classes/demon-hunter',
  '/guides/lock-stock-two-smoking-goblins',
  '/guides/a-noble-event',
  '/classes/paladin/holy',
  '/classes/paladin/protection',
  '/classes/paladin/retribution',
  '/classes/rogue/subtlety',
  '/classes/rogue/assassination',
  '/classes/rogue/outlaw',
  '/classes/hunter/beast-mastery',
  '/classes/hunter/marksmanship',
  '/classes/hunter/survival',
  '/classes/warrior/arms',
  '/classes/warrior/fury',
  '/classes/warrior/protection',
  '/classes/mage/arcane',
  '/classes/mage/fire',
  '/classes/mage/frost',
  '/classes/shaman/elemental',
  '/classes/shaman/enhancement',
  '/classes/shaman/restoration',
  '/classes/druid/balance',
  '/classes/druid/feral',
  '/classes/druid/guardian',
  '/classes/druid/restoration',
  '/classes/monk/brewmaster',
  '/classes/monk/mistweaver',
  '/classes/monk/windwalker',
  '/classes/priest/discipline',
  '/classes/priest/holy',
  '/classes/priest/shadow',
  '/classes/warlock/affliction',
  '/classes/warlock/demonology',
  '/classes/warlock/destruction',
  '/classes/death-knight/blood',
  '/classes/death-knight/frost',
  '/classes/death-knight/unholy',
  '/classes/demon-hunter/havoc',
  '/classes/demon-hunter/vengeance',
] as const

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return routes.map((path) => ({
    url: `${siteUrl}${path}`,
    lastModified: now,
  }))
}
